name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches_ignore: []

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup black environment
        run: conda create --quiet --name black black

      - name: Check formatting with black
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check gcpflask

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup testing environment
        run: conda create --quiet --name testing pytest

      - name: Test gcp-flask-stanford
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate testing
          pip install -r requirements.txt
          pytest -sv test_*.py
